In [1]:
import pandas as pd
import numpy as np

In [2]:
df_t2=pd.read_excel('Book1_with_column_names.xlsx')

In [3]:
df_t2.head()

,Run_ID (SRR),BioSample_ID (SAMN),Age,Read_Length,Total_Reads,Total_Bases,Institution,Developmental_Stage,Experiment_ID (SRX),SRX1074799,2015-07-05 00:00:00,2015-06-2623:48:00Z,Flowers,Flowers.1,hermaphrodite,Unnamed: 15,ILLUMINA,SAMN03784589,Unnamed: 18,Unnamed: 19
0,2,SRR2080095,SAMN03784590,3-month,202,3.63 G,2.42 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074800,2015-07-05,2015-06-2623:43:00Z,Leaves,Leaves,NaN,NaN,ILLUMINA,SAMN03784590,NaN,NaN
1,3,SRR2080096,SAMN03784593,3-month,202,3.28 G,2.20 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074801,2015-07-05,2015-06-2623:42:00Z,Roots,Roots,hermaphrodite,NaN,ILLUMINA,SAMN03784593,NaN,NaN
2,4,SRR2080097,SAMN03784594,2 weeks,202,3.81 G,2.56 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Seedling,SRX1074802,2015-07-05,2015-06-2623:47:00Z,Seedlings,Seedling (entire plants),hermaphrodite,NaN,ILLUMINA,SAMN03784594,NaN,Germination on Murashige & Skoog medium
3,5,SRR2080098,SAMN03784591,12 and 60-yr-old,200,14.42 G,9.68 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074803,2015-11-04,2015-10-3018:12:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,ILLUMINA,SAMN03784591,NaN,NaN
4,6,SRR2080099,SAMN03784592,12 and 60-yr-old,201,13.51 G,8.95 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074804,2016-02-12,2016-02-0715:37:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,ILLUMINA,SAMN03784592,NaN,NaN

In [4]:
df_t2.isnull().sum().sum()

85

In [10]:
df_t2.isnull().sum()[df_t2.isnull().sum()>0]

hermaphrodite     2
Unnamed: 15      19
ILLUMINA         14
SAMN03784589     14
Unnamed: 18      19
Unnamed: 19      17
dtype: int64

In [17]:
df_t2=df_t2.replace(["","NA","N/A","null","None","na","NAN"],
                    np.nan)

In [18]:
df_t2

,Run_ID (SRR),BioSample_ID (SAMN),Age,Read_Length,Total_Reads,Total_Bases,Institution,Developmental_Stage,Experiment_ID (SRX),SRX1074799,2015-07-05 00:00:00,2015-06-2623:48:00Z,Flowers,Flowers.1,hermaphrodite,Unnamed: 15,ILLUMINA,SAMN03784589,Unnamed: 18,Unnamed: 19
0,2,SRR2080095,SAMN03784590,3-month,202,3.63 G,2.42 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074800,2015-07-05,2015-06-2623:43:00Z,Leaves,Leaves,NaN,NaN,ILLUMINA,SAMN03784590,NaN,NaN
1,3,SRR2080096,SAMN03784593,3-month,202,3.28 G,2.20 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074801,2015-07-05,2015-06-2623:42:00Z,Roots,Roots,hermaphrodite,NaN,ILLUMINA,SAMN03784593,NaN,NaN
2,4,SRR2080097,SAMN03784594,2 weeks,202,3.81 G,2.56 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Seedling,SRX1074802,2015-07-05,2015-06-2623:47:00Z,Seedlings,Seedling (entire plants),hermaphrodite,NaN,ILLUMINA,SAMN03784594,NaN,Germination on Murashige & Skoog medium
3,5,SRR2080098,SAMN03784591,12 and 60-yr-old,200,14.42 G,9.68 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074803,2015-11-04,2015-10-3018:12:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,ILLUMINA,SAMN03784591,NaN,NaN
4,6,SRR2080099,SAMN03784592,12 and 60-yr-old,201,13.51 G,8.95 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074804,2016-02-12,2016-02-0715:37:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,ILLUMINA,SAMN03784592,NaN,NaN
5,7,SRR2080127,SAMN03784591,12 and 60-yr-old,200,3.23 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074825,2016-06-27,2015-06-2715:33:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
6,8,SRR2080128,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074825,2016-06-27,2015-06-2715:30:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
7,9,SRR2080131,SAMN03784591,12 and 60-yr-old,200,3.23 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074834,2015-07-28,2015-06-2720:19:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
8,10,SRR2080132,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074835,2015-07-28,2015-06-2720:40:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
9,11,SRR2080137,SAMN03784591,12 and 60-yr-old,200,3.77 G,2.53 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074836,2015-07-28,2015-06-2720:45:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
10,12,SRR2080138,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074837,2015-07-28,2015-06-2720:45:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
11,13,SRR2080148,SAMN03784592,12 and 60-yr-old,200,3.27 G,2.20 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074851,2015-07-28,2015-06-2722:33:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
12,14,SRR2080149,SAMN03784592,12 and 60-yr-old,200,3.22 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074852,2015-07-28,2015-06-2722:35:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
13,15,SRR2080150,SAMN03784592,12 and 60-yr-old,202,3.79 G,2.53 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074853,2015-07-28,2015-06-2722:59:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
14,16,SRR2080151,SAMN03784592,12 and 60-yr-old,202,3.23 G,2.16 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074854,2015-07-28,2015-06-2722:59:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
15,17,SRR2080153,SAMN03784589,12-yr-old,202,2.77 G,1.84 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",adult,SRX1074855,2015-07-28,2015-06-2723:04:00Z,Flowers,Flowers,hermaphrodite,NaN,NaN,NaN,NaN,NaN
16,18,SRR2080154,SAMN03784590,3-month,202,3.63 G,2.42 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Young plants,SRX1074856,2015-07-28,2015-06-2723:08:00Z,Leaves,Leaves,NaN,NaN,NaN,NaN,NaN,NaN
17,19,SRR2080155,SAMN03784593,3-month,202,3.28 G,2.20 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Young plants,SRX1074857,2015-07-28,2015-06-2723:08:00Z,Roots,Roots,hermaphrodite,NaN,NaN,NaN,NaN,NaN
18,20,SRR2080156,SAMN03784594,2 weeks,202,3.81 G,2.56 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Seedling,SRX1074858,2015-07-28,2015-06-2723:08:00Z,Seedlings,Seedling (entire plants),hermaphrodite,NaN,NaN,NaN,NaN,Germination on Murashige & Skoog medium

In [19]:
df_t2.isnull().sum().sum() # total missing values

85

In [20]:
df_t2.isna().sum().sum() # total nan values

85

In [25]:
df_t2.to_excel("edited_bookfilefile3.xlsx",index=True)

In [26]:
df_t2

,Run_ID (SRR),BioSample_ID (SAMN),Age,Read_Length,Total_Reads,Total_Bases,Institution,Developmental_Stage,Experiment_ID (SRX),SRX1074799,2015-07-05 00:00:00,2015-06-2623:48:00Z,Flowers,Flowers.1,hermaphrodite,Unnamed: 15,ILLUMINA,SAMN03784589,Unnamed: 18,Unnamed: 19
0,2,SRR2080095,SAMN03784590,3-month,202,3.63 G,2.42 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074800,2015-07-05,2015-06-2623:43:00Z,Leaves,Leaves,NaN,NaN,ILLUMINA,SAMN03784590,NaN,NaN
1,3,SRR2080096,SAMN03784593,3-month,202,3.28 G,2.20 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Young plants,SRX1074801,2015-07-05,2015-06-2623:42:00Z,Roots,Roots,hermaphrodite,NaN,ILLUMINA,SAMN03784593,NaN,NaN
2,4,SRR2080097,SAMN03784594,2 weeks,202,3.81 G,2.56 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Seedling,SRX1074802,2015-07-05,2015-06-2623:47:00Z,Seedlings,Seedling (entire plants),hermaphrodite,NaN,ILLUMINA,SAMN03784594,NaN,Germination on Murashige & Skoog medium
3,5,SRR2080098,SAMN03784591,12 and 60-yr-old,200,14.42 G,9.68 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074803,2015-11-04,2015-10-3018:12:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,ILLUMINA,SAMN03784591,NaN,NaN
4,6,SRR2080099,SAMN03784592,12 and 60-yr-old,201,13.51 G,8.95 Gb,UNIVERSITY OF SAO PAULO - LUIZ DE QUEIROZ COLLEGE,Adult,SRX1074804,2016-02-12,2016-02-0715:37:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,ILLUMINA,SAMN03784592,NaN,NaN
5,7,SRR2080127,SAMN03784591,12 and 60-yr-old,200,3.23 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074825,2016-06-27,2015-06-2715:33:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
6,8,SRR2080128,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074825,2016-06-27,2015-06-2715:30:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
7,9,SRR2080131,SAMN03784591,12 and 60-yr-old,200,3.23 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074834,2015-07-28,2015-06-2720:19:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
8,10,SRR2080132,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074835,2015-07-28,2015-06-2720:40:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
9,11,SRR2080137,SAMN03784591,12 and 60-yr-old,200,3.77 G,2.53 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074836,2015-07-28,2015-06-2720:45:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
10,12,SRR2080138,SAMN03784591,12 and 60-yr-old,200,3.71 G,2.49 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074837,2015-07-28,2015-06-2720:45:00Z,Stem Secondary Xylem,Secondary xylem from stem,hermaphrodite,NaN,NaN,NaN,NaN,NaN
11,13,SRR2080148,SAMN03784592,12 and 60-yr-old,200,3.27 G,2.20 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074851,2015-07-28,2015-06-2722:33:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
12,14,SRR2080149,SAMN03784592,12 and 60-yr-old,200,3.22 G,2.17 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074852,2015-07-28,2015-06-2722:35:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
13,15,SRR2080150,SAMN03784592,12 and 60-yr-old,202,3.79 G,2.53 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074853,2015-07-28,2015-06-2722:59:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
14,16,SRR2080151,SAMN03784592,12 and 60-yr-old,202,3.23 G,2.16 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Adult,SRX1074854,2015-07-28,2015-06-2722:59:00Z,Branch Secondary Xylem,Secondary xylem from branches,hermaphrodite,NaN,NaN,NaN,NaN,NaN
15,17,SRR2080153,SAMN03784589,12-yr-old,202,2.77 G,1.84 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",adult,SRX1074855,2015-07-28,2015-06-2723:04:00Z,Flowers,Flowers,hermaphrodite,NaN,NaN,NaN,NaN,NaN
16,18,SRR2080154,SAMN03784590,3-month,202,3.63 G,2.42 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Young plants,SRX1074856,2015-07-28,2015-06-2723:08:00Z,Leaves,Leaves,NaN,NaN,NaN,NaN,NaN,NaN
17,19,SRR2080155,SAMN03784593,3-month,202,3.28 G,2.20 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Young plants,SRX1074857,2015-07-28,2015-06-2723:08:00Z,Roots,Roots,hermaphrodite,NaN,NaN,NaN,NaN,NaN
18,20,SRR2080156,SAMN03784594,2 weeks,202,3.81 G,2.56 Gb,"UNIVERSITY OF SÃO PAULO - ""LUIZ DE QUEIROZ"" CO...",Seedling,SRX1074858,2015-07-28,2015-06-2723:08:00Z,Seedlings,Seedling (entire plants),hermaphrodite,NaN,NaN,NaN,NaN,Germination on Murashige & Skoog medium

In [27]:
import os
os.getcwd()

'C:\\Users\\SWARA LAKSHMI J\\PROJECT ML 1'