In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df= pd.read_excel(' FILE 1 teak working genes con_sorted_(2).xlsx')

In [21]:
import os
os.getcwd()

'C:\\Users\\SWARA LAKSHMI J\\PROJECT ML 1'

In [27]:
df.head()

,Gene_ID,branch12yr_SRR2080148,branch12yr_SRR2080149,branch60yr_SRR2080150,branch60yr_SRR2080151,flowers_SRR2080094,leaves_SRR2080095,roots_SRR2080096,seedlings_SRR2080097,stem12yr_SRR2080131,stem12yr_SRR2080132,stem60yr_SRR2080137,stem60yr_SRR2080138
0,Tg01g00010,0.947526,0.214594,0.260706,0.146897,0.289305,1.17831,0.408811,0.221877,0.221030,0.230644,0.173426,0.257679
1,Tg01g00020,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Tg01g00030,18.810400,17.392500,15.470800,16.664400,17.564600,10.99400,14.011400,20.792700,7.618540,3.355960,16.184200,12.528500
3,Tg01g00040,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Tg01g00050,2.498590,0.740532,0.618493,0.818552,1.356430,4.74561,3.009140,1.590730,0.845208,0.826855,0.851460,0.512924

In [28]:
df_log = np.log2(df + 1)

print("Normalization complete.")
print("Max value before:", df.values.max())
print("Max value after:", df_log.values.max())
df_log.head()

TypeError: can only concatenate str (not "int") to str

In [29]:
df.dtypes

Gene_ID                   object
branch12yr_SRR2080148    float64
branch12yr_SRR2080149    float64
branch60yr_SRR2080150    float64
branch60yr_SRR2080151    float64
flowers_SRR2080094       float64
leaves_SRR2080095        float64
roots_SRR2080096         float64
seedlings_SRR2080097     float64
stem12yr_SRR2080131      float64
stem12yr_SRR2080132      float64
stem60yr_SRR2080137      float64
stem60yr_SRR2080138      float64
dtype: object

In [34]:
num_cols=df.select_dtypes(include="number").columns
print("numeric columns")
print(num_cols)
df[num_cols]=np.log2(df[num_cols]+1)
print(df.head())

numeric columns
Index(['branch12yr_SRR2080148', 'branch12yr_SRR2080149',
       'branch60yr_SRR2080150', 'branch60yr_SRR2080151', 'flowers_SRR2080094',
       'leaves_SRR2080095', 'roots_SRR2080096', 'seedlings_SRR2080097',
       'stem12yr_SRR2080131', 'stem12yr_SRR2080132', 'stem60yr_SRR2080137',
       'stem60yr_SRR2080138'],
      dtype='object')
      Gene_ID  branch12yr_SRR2080148  branch12yr_SRR2080149  \
0  Tg01g00010               0.961643               0.280474
1  Tg01g00020               0.000000               0.000000
2  Tg01g00030               4.308186               4.201046
3  Tg01g00040               0.000000               0.000000
4  Tg01g00050               1.806774               0.799528

   branch60yr_SRR2080150  branch60yr_SRR2080151  flowers_SRR2080094  \
0               0.334232               0.197736            0.366594
1               0.000000               0.000000            0.000000
2               4.041839               4.142773            4.214482
3               0.000000               0.000000            0.000000
4               0.694651               0.862790            1.236603

   leaves_SRR2080095  roots_SRR2080096  seedlings_SRR2080097  \
0           1.123209          0.494478              0.289099
1           0.000000          0.000000              0.000000
2           3.584241          3.907987              4.445773
3           0.000000          0.000000              0.000000
4           2.522460          2.003293              1.373359

   stem12yr_SRR2080131  stem12yr_SRR2080132  stem60yr_SRR2080137  \
0             0.288099             0.299413             0.230727
1             0.000000             0.000000             0.000000
2             3.107443             2.122991             4.103011
3             0.000000             0.000000             0.000000
4             0.883783             0.869362             0.888663

   stem60yr_SRR2080138
0             0.330764
1             0.000000
2             3.757930
3             0.000000
4             0.597340

In [35]:
df.to_excel("file2lognormalised.xlsx",index=False)

In [36]:
df.head()

,Gene_ID,branch12yr_SRR2080148,branch12yr_SRR2080149,branch60yr_SRR2080150,branch60yr_SRR2080151,flowers_SRR2080094,leaves_SRR2080095,roots_SRR2080096,seedlings_SRR2080097,stem12yr_SRR2080131,stem12yr_SRR2080132,stem60yr_SRR2080137,stem60yr_SRR2080138
0,Tg01g00010,0.961643,0.280474,0.334232,0.197736,0.366594,1.123209,0.494478,0.289099,0.288099,0.299413,0.230727,0.330764
1,Tg01g00020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Tg01g00030,4.308186,4.201046,4.041839,4.142773,4.214482,3.584241,3.907987,4.445773,3.107443,2.122991,4.103011,3.757930
3,Tg01g00040,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Tg01g00050,1.806774,0.799528,0.694651,0.862790,1.236603,2.522460,2.003293,1.373359,0.883783,0.869362,0.888663,0.597340

In [2]:
import pandas as pd
df= pd.read_excel(' FILE 1 teak working genes con_sorted_(2).xlsx')

In [3]:
df_t = df.T

In [4]:
df_t.head()

,0,1,2,3,4,5,6,7,8,9,...,35834,35835,35836,35837,35838,35839,35840,35841,35842,35843
Gene_ID,Tg01g00010,Tg01g00020,Tg01g00030,Tg01g00040,Tg01g00050,Tg01g00060,Tg01g00070,Tg01g00080,Tg01g00090,Tg01g00100,...,TgUn908g00020,TgUn909g00010,TgUn910g00010,TgUn910g00020,TgUn910g00030,TgUn912g00010,TgUn913g00010,TgUn913g00020,TgUn914g00010,TgUn916g00010
branch12yr_SRR2080148,0.947526,0.0,18.8104,0.0,2.49859,2.07545,1.42832,1.48462,0.35981,0.0,...,0.043687,8.71863,11.0959,1.60303,0.397055,5.10498,1.85315,0.0,0.286351,0.0
branch12yr_SRR2080149,0.214594,0.0,17.3925,0.0,0.740532,5.1467,0.648307,0.72243,0.0,0.141313,...,0.499616,4.39834,2.07424,0.33592,0.0,3.50482,1.82334,0.0,0.0,0.0
branch60yr_SRR2080150,0.260706,0.0,15.4708,0.0,0.618493,3.64701,0.376167,0.238669,0.0,0.012716,...,0.607778,6.0204,5.21831,0.349097,0.0,3.40542,1.66984,0.0,0.110734,0.0
branch60yr_SRR2080151,0.146897,0.0,16.6644,0.0,0.818552,5.96584,0.597108,0.301012,0.0,0.0,...,0.659697,3.87519,7.55136,0.426738,0.0,3.70971,1.61684,0.0,0.059319,0.0

In [17]:
df= pd.read_excel('expression_datafinal.xlsx')

In [19]:
df.head()

,Gene_ID,branch12yr_SRR2080148,branch12yr_SRR2080149,branch60yr_SRR2080150,branch60yr_SRR2080151,flowers_SRR2080094,leaves_SRR2080095,roots_SRR2080096,seedlings_SRR2080097,stem12yr_SRR2080131,stem12yr_SRR2080132,stem60yr_SRR2080137,stem60yr_SRR2080138
0,Tg01g00010,0.961643,0.280474,0.334232,0.197736,0.366594,1.123209,0.494478,0.289099,0.288099,0.299413,0.230727,0.330764
1,Tg01g00020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Tg01g00030,4.308186,4.201046,4.041839,4.142773,4.214482,3.584241,3.907987,4.445773,3.107443,2.122991,4.103011,3.757930
3,Tg01g00040,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Tg01g00050,1.806774,0.799528,0.694651,0.862790,1.236603,2.522460,2.003293,1.373359,0.883783,0.869362,0.888663,0.597340

In [26]:
df_new=df.T

In [27]:
df_new.head()

,0,1,2,3,4,5,6,7,8,9,...,35834,35835,35836,35837,35838,35839,35840,35841,35842,35843
Gene_ID,Tg01g00010,Tg01g00020,Tg01g00030,Tg01g00040,Tg01g00050,Tg01g00060,Tg01g00070,Tg01g00080,Tg01g00090,Tg01g00100,...,TgUn908g00020,TgUn909g00010,TgUn910g00010,TgUn910g00020,TgUn910g00030,TgUn912g00010,TgUn913g00010,TgUn913g00020,TgUn914g00010,TgUn916g00010
branch12yr_SRR2080148,0.961643,0.0,4.308186,0.0,1.806774,1.620798,1.279959,1.313025,0.443405,0.0,...,0.061689,3.280753,3.596446,1.380192,0.482389,2.609987,1.512556,0.0,0.363284,0.0
branch12yr_SRR2080149,0.280474,0.0,4.201046,0.0,0.799528,2.619812,0.720985,0.784445,0.0,0.190694,...,0.584593,2.432516,1.62023,0.417834,0.0,2.171469,1.497403,0.0,0.0,0.0
branch60yr_SRR2080150,0.334232,0.0,4.041839,0.0,0.694651,2.216303,0.460656,0.308791,0.0,0.01823,...,0.685068,2.811553,2.636523,0.431994,0.0,2.13928,1.416753,0.0,0.151513,0.0
branch60yr_SRR2080151,0.197736,0.0,4.142773,0.0,0.86279,2.800297,0.675462,0.379634,0.0,0.0,...,0.73092,2.285458,3.096154,0.51272,0.0,2.235638,1.387826,0.0,0.083138,0.0

In [29]:
df_new=df.to_excel("file1newlogT.xlsx",index=False)

In [41]:
import pandas as pd

# 1. Load your log-normalized file
df= pd.read_excel(' FILE 1 teak working genes con_sorted_(2).xlsx')

# 2. Identify the numeric columns (skipping the Gene_ID column)
numeric_cols = df.columns[1:]

# 3. Filter out rows where the sum of all sample values is 0
# This keeps only genes that are expressed in at least one sample
df_cleaned = df[df[numeric_cols].sum(axis=1) > 0]




print(f"Original genes: {len(df)}")
print(f"Genes removed: {len(df) - len(df_cleaned)}")
print(f"Remaining genes: {len(df_cleaned)}")

Original genes: 35844
Genes removed: 3258
Remaining genes: 32586

In [42]:
df_cleaned.to_excel("ExpressionNew.xlsx",index=False)

In [43]:
num_cols=df_cleaned.select_dtypes(include="number").columns
print("numeric columns")
print(num_cols)
df_cleaned[num_cols]=np.log2(df_cleaned[num_cols]+1)
print(df_cleaned.head())

numeric columns
Index(['branch12yr_SRR2080148', 'branch12yr_SRR2080149',
       'branch60yr_SRR2080150', 'branch60yr_SRR2080151', 'flowers_SRR2080094',
       'leaves_SRR2080095', 'roots_SRR2080096', 'seedlings_SRR2080097',
       'stem12yr_SRR2080131', 'stem12yr_SRR2080132', 'stem60yr_SRR2080137',
       'stem60yr_SRR2080138'],
      dtype='object')
      Gene_ID  branch12yr_SRR2080148  branch12yr_SRR2080149  \
0  Tg01g00010               0.961643               0.280474
2  Tg01g00030               4.308186               4.201046
4  Tg01g00050               1.806774               0.799528
5  Tg01g00060               1.620798               2.619812
6  Tg01g00070               1.279959               0.720985

   branch60yr_SRR2080150  branch60yr_SRR2080151  flowers_SRR2080094  \
0               0.334232               0.197736            0.366594
2               4.041839               4.142773            4.214482
4               0.694651               0.862790            1.236603
5               2.216303               2.800297            1.513849
6               0.460656               0.675462            4.451739

   leaves_SRR2080095  roots_SRR2080096  seedlings_SRR2080097  \
0           1.123209          0.494478              0.289099
2           3.584241          3.907987              4.445773
4           2.522460          2.003293              1.373359
5           2.565444          2.149367              1.732586
6           3.670682          3.176503              2.936966

   stem12yr_SRR2080131  stem12yr_SRR2080132  stem60yr_SRR2080137  \
0             0.288099             0.299413             0.230727
2             3.107443             2.122991             4.103011
4             0.883783             0.869362             0.888663
5             4.065788             3.955852             2.452139
6             0.817481             1.320358             1.021473

   stem60yr_SRR2080138
0             0.330764
2             3.757930
4             0.597340
5             2.640725
6             0.646304

C:\Users\SWARA LAKSHMI J\AppData\Local\Temp\ipykernel_9100\3132444075.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[num_cols]=np.log2(df_cleaned[num_cols]+1)

In [47]:
df.to_excel('EXPRESSEDGENES0 GENES REMOVES AND LOG NORMALISED.xlsx'),index=False)

SyntaxError: unmatched ')' (3073961177.py, line 1)

In [48]:
df_cleaned.to_excel("ExpressionNewFULLYNEW.xlsx",index=False)